### ISSUE TITLE
B365 HS

### ISSUE THREAD

**Issue by mjgerace** [teocns/quidextension#1]
No easy way to contact you, so I am writing to you here. I am willing to pay $50 for the solution to the bet365 handshake - email geracemi at (sehs) [dot] net <-- no () around the sehs.

**Comment by efialtisgr** [comment]
im willing to pay you as much as you are happy mate, really need this :) please mail me at footballtradergr at gmail dot com

**Comment by Smart828** [comment]
I think I found a temporary solution. If you are interested write to sergeev828 at gmail dot com
